### ISSUE TITLE
As a user, I need a better tagging system

### ISSUE THREAD

**Issue by ozramos** [nextcheckbox/nextcheckbox#54]
Tagging will do two things: it'll let the community tag a large number of services, which will help the bot find what it needs, and after enough samples will allow for building an auto tagging agent. We'll use Tensorflow to analyze service content for autotagging in a future story.

This story will deal with a simple tagging system that lets users tag services like they do Twitter posts.

## Taxonomies route
- [x] Start `/admin/taxonomies`
- [x] Add a "get all tags" button, which loops through all services and extracts unique tags
- [x] Display tags in a list that when clicked takes you to `/services?tags=$tag`

## Tasks
- [ ] Create a new collection on firebase to hold a list of valid tags
- [ ] Use the [Chip component within a select field](https://vuetifyjs.com/en/components/chips) that contains the complete list of tags from firebase
- [ ] Create a menu of common tags
- [ ] Link these tags in Dialogflow

**Comment by ozramos** [comment]
I screwed up the repo trying to get this to work 😞 I was overengineering this anyways so I'm going to start a new story
