### ISSUE TITLE
As a user, I want to embed maps

### ISSUE THREAD

**Issue by ozramos** [nextcheckbox/nextcheckbox#69]
This story deals with the ability to embed collections (#68) and will primarily focus on embedding through an iframe.

## Tasks
- [x] Setup a layout system (one for default and another for /embed)
- [x] Create an /embed route that uses a full screen service map
- [x] Pull services using `?category&tag`
- [x] Pull services using `?serviceID`
- [x] Embed collections

## Embed button
- [x] Add embed icons to service listings
- [x] Add embed icons to collections
- [x] On embed icon click, show a popup with code and instructions
