### ISSUE TITLE
As a user, I want to remove services from collections

### ISSUE THREAD

**Issue by ozramos** [nextcheckbox/nextcheckbox#72]
## Tasks
- [x] Add firestore rules (only owner should be able to remove)
- [x] Remove the service from the current list
- [x] Remove it from firebase
