### ISSUE TITLE
Optimize service loading by creating local caches

### ISSUE THREAD

**Issue by ozramos** [nextcheckbox/nextcheckbox#73]
Let's assume that during the duration of a users session, all services do not get updated. With this in mind, let's create a "servicesCache" to store services as they are loaded by various parts of the app. Then, instead of loading services from firebase first check the cache

## Tasks
- [x] Store a session cache
- [x] Persist cache in localStorage, then update from firebase

## Routes
- [x] /services/
- [x] /collections/
- [x] Remove flicker effect
