### ISSUE TITLE
As a user, I want to sort collection items

### ISSUE THREAD

**Issue by ozramos** [nextcheckbox/nextcheckbox#74]
## Tasks
- [x] Add up/down arrows to services inside of collections to increase their ordering
- [x] Sort services by order
- [x] Persist order to firestore (skip success message and only show errors)
