### ISSUE TITLE
As an admin, I want to inject meta info into index.html

### ISSUE THREAD

**Issue by ozramos** [nextcheckbox/nextcheckbox#81]
This story deals with injecting meta info into the index.html through firebase functions. The reason I'm doing this is because I utterly failed to get Nuxt to do SSR on firebase (https://github.com/nextcheckbox/nuxt)...which would be heavier weight anyways!

## Prep
- [x] Create an NPM script that moves `/dist/index.html` and `/public/metatags.json` into `/functions/dist/`
- [x] Add a string to index.html to inject meta info into
- [x] Create a `/public/metatags.json` that matches routes (eg `/`, `/services`, `/tools/export`)

## "Pages"
- [x] Route all firebase hosting urls into a `ssrPage` function
- [x] Inject matched meta info

## "Services"
- [x] Create a `ssrService` function matching `/services/*`
- [x] Load service through functions
- [x] Inject meta info
- [x] Since we already have the service inject it into a `<script>` tag as `ssrPayload.service`
- [x] In the app, if `ssrPayload` exists then just use that (instead of using firebase)
- [x] Use small Twitter icon for services

## "Collections"
- [x] Do the above for collections
